config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :products
  resources :orders
  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true
  # Descrivo le relazioni tra entità
  has_many :orders
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :address)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  customers_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
          <td><%= customer.name %></td>
          <td><%= customer.email %></td>
          <td><%= customer.phone %></td>
          <td><%= customer.address %></td>
        <td><%=l customer.created_at, format: :long %></td>
        <td>
          <%= link_to customer_path(customer), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_customer_path(customer), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to customer_path(customer), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_customer_path,
            class: 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @customer.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @customer.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @customer.phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @customer.address %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              customers_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_customer_path(@customer), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              customer_path(@customer),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>