config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :products
  resources :orders
  resources :customers

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :code, :customer, :price, presence: true
  validates :code, uniqueness: true 
  # Descrivo le relazioni tra entità
  belongs_to :customer
  has_many :order_items
  has_many :products, through: :order_items

  def human_code
    "#{code} - #{customer.name}"
  end

  def total_price
    if order_items.present?
      final_prices = []
      order_items.each do | order_item |
        final_prices << (order_item.product.price - (order_item.product.price * (order_item.discount / 100))) * order_item.quantity
      end
      final_prices.sum
    else
      price
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:code, :description, :price, :shipped_date, :customer_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :code, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :code, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price, value: f.object.total_price, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shipped_date, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :shipped_date, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :customer_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select(:customer_id, Customer.all, :id, :name, {}, {class: 'text_field form-control'}) %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  orders_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:shipped_date) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
          <td><%= order.code %></td>
          <td><%= order.description %></td>
          <td><%= order.total_price %></td>
          <td><%= order.shipped_date %></td>
          <td><%= order.customer.name %></td>
        <td><%=l order.created_at, format: :long %></td>
        <td>
          <%= link_to order_path(order), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_order_path(order), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to order_path(order), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_order_path,
            class: 'btn btn-primary' %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:code) %></dt>
      <dd><pre class="prettyprint"><%= @order.code %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @order.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @order.total_price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:shipped_date) %></dt>
      <dd><pre class="prettyprint"><%= @order.shipped_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:customer_id) %></dt>
      <dd><pre class="prettyprint"><%= @order.customer.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              orders_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_order_path(@order), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              order_path(@order),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>