config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :products
  resources :orders
  resources :customers

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  def incremental_discounts
    case
    when (5..9).include?(quantity)
      (product.price - (product.price / 100 * 5)).to_f
    when (10..19).include?(quantity)
      (product.price - (product.price / 100 * 10)).to_f
    when quantity > 19 
      (product.price - (product.price / 100 * 20)).to_f
    else
      product.price
    end
  end

  def line_price
    to_discount = incremental_discounts * quantity
    to_discount - (to_discount / 100 * discount)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:product_id, :order_id, :quantity, :discount)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for @order_item, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :product_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select(:product_id, Product.all, :id, :test, {}, {class: 'text_field form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select(:order_id, Order.all, :id, :human_code, {}, {class: 'text_field form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :quantity, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :discount, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :discount, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  order_items_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/order_items/index.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:order_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:discount) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.id %></td>
          <td><%= order_item.product.test %></td>
          <td><%= order_item.order.human_code %></td>
          <td><%= best_in_place order_item, :quantity, :as => :input %> 
          <td><%= best_in_place order_item, :discount, :as => :input %> 
          <td id="lp<%= order_item.id %>"><%= order_item.line_price %></td>
        <td><%=l order_item.created_at, format: :long %></td>
        <td>
          <%= link_to order_item_path(order_item), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_order_item_path(order_item), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to order_item_path(order_item), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_order_item_path,
            class: 'btn btn-primary' %>

app/views/order_items/new.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/order_items/show.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:product_id) %></dt>
      <dd><pre class="prettyprint"><%= @order_item.product.test %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:order_id) %></dt>
      <dd><pre class="prettyprint"><%= @order_item.order.human_code %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @order_item.quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:discount) %></dt>
      <dd><pre class="prettyprint"><%= @order_item.discount %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @order_item.line_price %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              order_items_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_order_item_path(@order_item), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              order_item_path(@order_item),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>