config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :products
  resources :orders
  resources :customers

end

app/models/product.rb
class Product < ActiveRecord::Base
  MATERIALS = ["METALLO", "LEGNO", "GOMMA", "PLASTICA", "CALCESTRUZZO"]
  has_many :order_items
  has_many :orders, through: :order_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:test, :operator, :material, :price, :va, :test_date)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :test, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :test, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :operator, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :operator, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :material, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select :material, Product::MATERIALS, :to_s, :to_s, {}, {class: 'text_field form-control'} %> 
     </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :va, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :va, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :test_date, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :test_date, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  products_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:test) %></th>
      <th><%= model_class.human_attribute_name(:operator) %></th>
      <th><%= model_class.human_attribute_name(:material) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:va) %></th>
      <th><%= model_class.human_attribute_name(:test_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
          <td><%= product.test %></td>
          <td><%= product.operator %></td>
          <td><%= product.material %></td>
          <td><%= product.price %></td>
          <td><%= product.va %></td>
          <td><%= product.test_date %></td>
        <td><%=l product.created_at, format: :long %></td>
        <td>
          <%= link_to product_path(product), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_product_path(product), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to product_path(product), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_product_path,
            class: 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:test) %></dt>
      <dd><pre class="prettyprint"><%= @product.test %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:operator) %></dt>
      <dd><pre class="prettyprint"><%= @product.operator %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:material) %></dt>
      <dd><pre class="prettyprint"><%= @product.material %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @product.price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:va) %></dt>
      <dd><pre class="prettyprint"><%= @product.va %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:test_date) %></dt>
      <dd><pre class="prettyprint"><%= @product.test_date %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              products_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_product_path(@product), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              product_path(@product),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>